language: python
python:
  - "3.6" # Until 2021-12-23 at latest
  - "3.7" # supported until  2023-06-27 at latest
  - "3.8" # latest python version
dist: xenial
os: linux

install:
    - pip install flake8
    
script:
    - flake8 wmfconfigreader.py --ignore E402,F401,W503,E722
